
#docker compose --env-file .env up -d

services:
  consensus:
    build:
      context: .
      dockerfile: Dockerfile
    image: consensus:latest
    container_name: consensus
    ports:
      - "8585:8080"
    # Set an env var of CONSENSUS_APIKEY with your key value first.
    environment:
      - Consensus__ApiEndpoint=${Consensus__ApiEndpoint}
      - Consensus__ApiKey=${Consensus__ApiKey}
      - Consensus__CleanupCrontab=${Consensus__CleanupCrontab}
      - Consensus__Models__0=${Consensus__Models__0}
      - Consensus__Models__1=${Consensus__Models__1}
      - Consensus__Models__2=${Consensus__Models__2}
      - Consensus__Models__3=${Consensus__Models__3}
      - Consensus__Models__4=${Consensus__Models__4}
      - Consensus__Models__5=${Consensus__Models__5}
      - Consensus__Models__6=${Consensus__Models__6}
    volumes:
      - ./output:/app/output
    restart: unless-stopped